### ISSUE TITLE
Crash While Looking the Item List on the Advanced Vending Block

### ISSUE THREAD

**Issue by ghost** [kamildanak/VendingBlock#15]
I just click "Select" then scroll down the list, it crashed. here is the crash log:
[crash-2017-02-21_14.54.15-client.txt](https://github.com/kamildanak/VendingBlock/files/790129/crash-2017-02-21_14.54.15-client.txt)

**Comment by kamildanak** [comment]
Fixed in 5c0a6e9e278ff123ce964c3c85007c2323d9f062
Thank you for reporting.

**Comment by ghost** [comment]
Good! I will report all bugs if i can. Thanks. We are waiting for new release.
