### ISSUE TITLE
Visual Bug (Compatibility)

### ISSUE THREAD

**Issue by ghost** [kamildanak/VendingBlock#18]
I don't really know why does it happening... But it is happening when i install ItemPhysic mod and CreativeCore mods... I hope it has an easy solution :/ Hope solved. Thanks.
![visual bug](https://cloud.githubusercontent.com/assets/24831406/23225572/faf89d0c-f93a-11e6-8c01-d033b2176dcb.gif)

**Comment by ghost** [comment]
https://github.com/CreativeMD/ItemPhysic/issues/29

**Comment by kamildanak** [comment]
Fixed in e8bde8244d06a9d38cf4849a3b800118bf613d1c

**Comment by ghost** [comment]
thanks a lot...
