### ISSUE TITLE
Buying enderpay credits seem to bug out when holding an item

### ISSUE THREAD

**Issue by SeriousCreeper** [kamildanak/VendingBlock#19]
Heya,

i'm trying out Vending Block + Enderpay, but it seems like if i right click the vending block with an item in my hand, i am storing the item inside the vending block. 

Let me know if you need any additional information. Using the latest versions of enderpay/vending block. 

Thanks,
SC

**Comment by kamildanak** [comment]
Fixed in 3864098497c58451d277aa9e1e4246dc880e3b14

**Comment by SeriousCreeper** [comment]
Thanks!
Would this be ported to the 1.10.2 version as well?

**Comment by kamildanak** [comment]
Yes, I just uploaded fix for 1.10.2

**Comment by SeriousCreeper** [comment]
Thank you so much!
