### ISSUE TITLE
Conflict bewteen Vending Machines Mod and Spice of Life

### ISSUE THREAD

**Issue by MFernflower** [kamildanak/VendingBlock#2]
When inserting rotting flesh into the sell or buy slot of a vender block this happens: http://pastebin.com/GnEBbaHa and will happen to any player who approaches the block

**Comment by kamilx3** [comment]
You are using old version of Vending (1.2.1b instead of 1.2.2b)
Please download the update and check if it helps.
The issue was fixed in this commit: 5fa6607772e65202b198322be2a9828979a3e15c

**Comment by MFernflower** [comment]
Keeping this open until server admin updates modpack and can verify it is working.

**Comment by MFernflower** [comment]
Seems to be fixed.
