### ISSUE TITLE
[Server-side] [1.10.2-1.4.3] java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n

### ISSUE THREAD

**Issue by lurr** [kamildanak/VendingBlock#22]
Crashlog: http://pastebin.com/EL3XwUjK

Caused by these lines of code: https://github.com/kamildanak/VendingBlock/blob/master/src/main/java/info/jbcs/minecraft/vending/block/BlockVendingMachine.java#L456-L460

**Comment by kamildanak** [comment]
Fixed in ee16397ca4be5d60ab927ca61dfd7fcba20544f7
