### ISSUE TITLE
buying bug, seller loss.

### ISSUE THREAD

**Issue by terrybougard** [kamildanak/VendingBlock#25]
Hi! There's a bug

 lets say the buy cost is 10 emeralds, it deducts correctly for the one who buys, but it only puts 1 emerald in the vending machine storage. so its a big loss for the seller.

 Thanks!

**Comment by walker-dev** [comment]
Yea for me this happends too :(

**Comment by kamildanak** [comment]
Fixed in 80b5ca95e8baaf726b70562dbe550ec2b47691ea
Thank you for reporting.
