### ISSUE TITLE
can't trade in a FTB region

### ISSUE THREAD

**Issue by Jay9519** [kamildanak/VendingBlock#26]
players can trade just fine in  an open area but once they protect the build around the vending block the players can't trade anymore.

Vending-1.11.2-1.4.3
FTButilities-1.1x-3.6.5
Spongeforge-1.11.2-2315-6.1.0-BETA-2410

**Comment by jtrent238** [comment]
You need to whitelist the Vending block in FTButilities

**Comment by kamildanak** [comment]
Correct.
"ftbu.claims.block.interact.vending.vendingmachine", "ftbu.claims.block.interact.vending.vendingmachineadvanced",
"ftbu.claims.block.interact.vending.vendingmachinemultiple"
