### ISSUE TITLE
Prob

### ISSUE THREAD

**Issue by ghost** [kamildanak/VendingBlock#32]
I am having an issue with Vending on my 1.12.2 server with spongeforge installed and the latest updated version of forge with this set  B:transfer_to_inventory=true the items don't transfer into the player's inventories just takes the credits but does not give the items, so is this a forge bug?

**Comment by JolyGoodDay** [comment]
Similar issue, did you try with empty inventory? 

When I use these vending blocks from the admin shop on HAC, I must have some specific slot empty. For example the redstone vending block goes to slot 1 on the hot bar, and the lapis one goes to slot 9 on the top row of inventory. If another item occupies that specific slot, the items from the vending machine will be voided into oblivion only taking my chips.

**Comment by KiriCattus** [comment]
Having a similar issue on our server too but it does work in creative mode.
Forge: 1.12.2-14.23.2.2611
Vending Blocks: 1.12.2-3.0.1.0
Ender Pay: 1.12.2-1.0.1.0
Spongeforge: Not used here.
Had an older version installed with older forge version and it failed to work there as well.
https://github.com/MinecraftModDevelopment/New-MMD-Public-Pack/issues/19

**Comment by kamildanak** [comment]
Thank you for reporting the issue.
I was able to reproduce the bug with only VendingBlock and EnderPay installed, it does not occur when in creative mode or when some specific slots are empty.
I fixed it in 953dfc2baf6df49858c3979138c6ae2e76e3c381. I will make sure that nothing new is broken after that commit, and upload the new version on Tuesday to Curseforge.
