### ISSUE TITLE
Clicking on $ show 0 even if a cost is already set

### ISSUE THREAD

**Issue by ExDomino** [kamildanak/VendingBlock#34]
If I click on the $ button and set a cost, all is working as expected (except the value in truncated and this is a really problem for bigs amounts like 123 456 credits that only show 123k) but if I click again on the $ button, I expect that the last amount I set was indicated, except I see a 0.

Version of your mods:
- Vending: 3.0.1.1
- EnderPay: 1.0.1.1

**Comment by kamildanak** [comment]
Fixed in 1322a81b7380f8dec0f75911e7a760e34587375c ([vending-1.12.2-3.0.1.2.jar](https://minecraft.curseforge.com/projects/vending-block/files/2614896)). Thank you for reporting the bug and sorry it took that long to fix.
