### ISSUE TITLE
Lock the buy and sell slots

### ISSUE THREAD

**Issue by BrAdministrated** [kamildanak/VendingBlock#38]
Is it possible to lock the buy/sell slots?  This will prevent the items being extracted by the Hopper.
Especially a problem with the advanced vending block.  You can select an emerald block, and the hopper will grab it out.  Essentially generating emerald blocks out of nothing.

**Comment by kamildanak** [comment]
Connecting hoppers directly to Vending Block should not be possible.
The only expected hopper integration is via Vending Block Storage Attachment.
I will disable it completely and upload the fixed version to CurseForge today.

**Comment by kamildanak** [comment]
Fixed in bf2aa8dfaef0d4ece236ba51a181f85799544919 ([vending-1.12.2-3.0.1.2.jar](https://minecraft.curseforge.com/projects/vending-block/files/2614896))
